import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { useRouter } from 'next/router'

export default function Counter() {
  
 const [number, setNumber] = useState(0);
 const searchParams = useSearchParams();
 const isUser = searchParams.get('username')
 const router = useRouter();

 useEffect(() => {
    if(!isUser) {
      router.push(
          '/'
      )
    }  
 }, [isUser])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          COUNTER PAGE&nbsp;
          <code className={styles.code}>Welcome {isUser}</code>
        </p>

        <div className={styles.grid}>
          <h2>
            The number is:
          </h2> 
          <p>
            {number}
          </p>
          
          <button onClick={() => setNumber(number + 1)}>Increment</button>
          <button onClick={() => setNumber(number - 1)}>Decrement</button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
